
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iigenwvxvvfoywrhbwms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZ2Vud3Z4dnZmb3l3cmhid21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDU0MTksImV4cCI6MjA2MjI4MTQxOX0.oRO2co015e5tiMIB3TtVlOliEv8eSBibUvhl8nrZyf8";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    flowType: 'pkce', // Using PKCE for better security and performance
    debug: false // Disable debug logs in production
  }
});

// Flag to track logout status to prevent automatic reconnection
export let isLogoutActive = false;

export const setLogoutActive = (status: boolean) => {
  isLogoutActive = status;
  
  // Store the logout status in sessionStorage to persist across page navigation
  try {
    if (typeof window !== 'undefined') {
      if (status) {
        sessionStorage.setItem('logoutActive', 'true');
      } else {
        sessionStorage.removeItem('logoutActive');
      }
    }
  } catch (e) {
    console.error("Error managing logout status in sessionStorage:", e);
  }
};

// Check if there's a stored logout status on initialization
if (typeof window !== 'undefined') {
  isLogoutActive = sessionStorage.getItem('logoutActive') === 'true';
}

// Cache for user data - prevents repeated database calls
export const userCache = new Map();

// Clear all user data from cache
export const clearUserCache = () => {
  console.log("🗑️ Nettoyage du cache utilisateur");
  userCache.clear();
  
  // Also clear any auth-related items from localStorage
  if (typeof window !== 'undefined') {
    try {
      // Liste des clés potentiellement liées à l'authentification
      const authKeys = ['supabase.auth.token', 'sb-iigenwvxvvfoywrhbwms-auth-token'];
      authKeys.forEach(key => {
        if (localStorage.getItem(key)) {
          console.log(`Suppression de ${key} du localStorage`);
          localStorage.removeItem(key);
        }
      });
    } catch (e) {
      console.error("Erreur lors du nettoyage du localStorage:", e);
    }
  }
};

// Expose admin methods for demo purposes - this is for demo accounts only
// In a real production app, these should be moved to a secure backend
if (typeof window !== 'undefined') {
  (supabase.auth as any).admin = {
    listUsers: async () => {
      // Pour les besoins de la démo, nous simulons cette fonction
      console.log("Admin listUsers called - this is a stub for demo purposes");
      
      // Tenter de récupérer les utilisateurs via une requête à profiles_unified
      try {
        const { data, error } = await supabase
          .from('profiles_unified')
          .select('id, email, is_demo')
          .eq('is_demo', true);
          
        if (error) {
          console.error("Erreur lors de la récupération des utilisateurs:", error);
          return { data: { users: [] }, error: null };
        }
        
        // Transformer les données pour correspondre à ce qu'attendrait auth.users
        const users = data.map(profile => ({
          id: profile.id,
          email: profile.email,
          user_metadata: { is_demo: true }
        }));
        
        return { data: { users }, error: null };
      } catch (err) {
        console.error("Erreur dans listUsers:", err);
        return { data: { users: [] }, error: null };
      }
    },
    // Utilisation de la méthode standard de déconnexion pour assurer la cohérence
    signOut: async () => {
      console.log("Admin signOut called - utilisation de la méthode standard de déconnexion");
      return await supabase.auth.signOut({ scope: 'global' });
    }
  };
}
