
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iigenwvxvvfoywrhbwms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZ2Vud3Z4dnZmb3l3cmhid21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDU0MTksImV4cCI6MjA2MjI4MTQxOX0.oRO2co015e5tiMIB3TtVlOliEv8eSBibUvhl8nrZyf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    flowType: 'pkce', // Using PKCE for better security and performance
    debug: false // Disable debug logs in production
  }
});

// Cache for user data - prevents repeated database calls
export const userCache = new Map();

// Clear all user data from cache
export const clearUserCache = () => {
  console.log("🗑️ Nettoyage du cache utilisateur");
  userCache.clear();
};

// Expose admin methods for demo purposes - this is for demo accounts only
// In a real production app, these should be moved to a secure backend
if (typeof window !== 'undefined') {
  (supabase.auth as any).admin = {
    listUsers: async () => {
      // Pour les besoins de la démo, nous simulons cette fonction
      console.log("Admin listUsers called - this is a stub for demo purposes");
      return { data: { users: [] }, error: null };
    },
    getUserByEmail: async (email: string) => {
      // Tenter d'obtenir l'utilisateur via l'email
      console.log("Récupération d'utilisateur par email:", email);
      try {
        const { data, error } = await supabase.auth.signInWithPassword({ 
          email, 
          password: 'demo123' // Utiliser mot de passe démo connu
        });
        
        if (error) {
          console.log("Erreur lors de la récupération d'utilisateur par email:", error);
          return { data: null, error };
        }
        
        // Se déconnecter immédiatement pour ne pas affecter l'état d'authentification
        await supabase.auth.signOut();
        
        return { data: { user: data.user }, error: null };
      } catch (err) {
        console.error("Erreur lors de getUserByEmail:", err);
        return { data: null, error: err };
      }
    },
    // Utilisation de la méthode standard de déconnexion pour assurer la cohérence
    signOut: async () => {
      console.log("Admin signOut called - utilisation de la méthode standard de déconnexion");
      return await supabase.auth.signOut();
    }
  };
}
