
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iigenwvxvvfoywrhbwms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZ2Vud3Z4dnZmb3l3cmhid21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDU0MTksImV4cCI6MjA2MjI4MTQxOX0.oRO2co015e5tiMIB3TtVlOliEv8eSBibUvhl8nrZyf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    flowType: 'pkce', // Using PKCE for better security and performance
    debug: false // Disable debug logs in production
  }
});

// Cache for user data - prevents repeated database calls
export const userCache = new Map();

// Helper for session management - supprimé car il crée des confusions
// et n'est pas nécessaire puisque nous utilisons directement supabase.auth.signOut()

// Expose admin methods for demo purposes - this is for demo accounts only
// In a real production app, these should be moved to a secure backend
if (typeof window !== 'undefined') {
  (supabase.auth as any).admin = {
    listUsers: async () => {
      // This is just a stub that will return empty results in the frontend
      // Real admin functionality would require backend implementation
      console.log("Admin listUsers called - this is a stub for demo purposes");
      return { data: { users: [] }, error: null };
    },
    // Ajout d'une méthode de déconnexion cohérente pour éviter les erreurs
    signOut: async () => {
      console.log("Admin signOut called - utilisation de la méthode standard");
      return await supabase.auth.signOut();
    }
  };
}
